#!/usr/bin/env python3
"""Extract plain text from vendored PDFs into corpus/_extracted/ sidecar files.

Purely a search-index aid for the companion MCP server (GenAI-Security-Advisor-MCP)
-- pypdf's extraction is not layout-aware (tables/columns often come out
garbled), so these .txt files are NEVER the citable source. The original PDF
(referenced by each sidecar's header comment) remains that. See
corpus/_extracted/README.md for the full caveat.

Run via `python scripts/extract_pdf_text.py` from the repo root, or let
.github/workflows/extract-pdf-text.yaml run it on every corpus/**.pdf change.
"""
import argparse
import os
import sys
from datetime import datetime, timezone

import yaml
from pypdf import PdfReader

EXTRACTED_ROOT = "_extracted"


def die(msg: str) -> None:
    print(f"[extract_pdf_text] ERROR: {msg}", file=sys.stderr)
    sys.exit(1)


def extracted_path(pdf_path: str) -> str:
    """corpus/foo/bar.pdf -> corpus/_extracted/foo/bar.pdf.txt"""
    assert pdf_path.startswith("corpus/")
    rest = pdf_path[len("corpus/"):]
    return os.path.join("corpus", EXTRACTED_ROOT, rest + ".txt")


def extract_one(repo_root: str, pdf_path: str, resource_id: str, license_: str) -> bool:
    abs_pdf = os.path.join(repo_root, pdf_path)
    if not os.path.isfile(abs_pdf):
        print(f"[extract_pdf_text] WARN: {pdf_path} not found, skipping", file=sys.stderr)
        return False

    out_rel = extracted_path(pdf_path)
    out_abs = os.path.join(repo_root, out_rel)
    os.makedirs(os.path.dirname(out_abs), exist_ok=True)

    reader = PdfReader(abs_pdf)
    pages = []
    for i, page in enumerate(reader.pages, start=1):
        text = page.extract_text() or ""
        pages.append(f"--- page {i} ---\n{text.strip()}")

    header = (
        f"# AUTO-GENERATED by scripts/extract_pdf_text.py -- DO NOT EDIT BY HAND\n"
        f"# source_pdf: {pdf_path}\n"
        f"# resource_id: {resource_id}\n"
        f"# license: {license_} (inherited from source PDF, see corpus/MANIFEST.yaml)\n"
        f"# extracted: {datetime.now(timezone.utc).strftime('%Y-%m-%d')}\n"
        f"#\n"
        f"# UNREVIEWED, LOSSY TEXT EXTRACTION -- for full-text search only.\n"
        f"# Tables, multi-column layout, and figures do not survive extraction\n"
        f"# reliably. Never quote this as the citable source -- fetch source_pdf\n"
        f"# above for anything that needs to be accurate.\n"
        f"\n"
    )

    with open(out_abs, "w", encoding="utf-8") as f:
        f.write(header)
        f.write("\n\n".join(pages))
        f.write("\n")

    print(f"[extract_pdf_text] wrote {out_rel} ({len(pages)} pages)")
    return True


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo-root", default=".")
    args = ap.parse_args()

    repo_root = os.path.abspath(args.repo_root)
    manifest_path = os.path.join(repo_root, "corpus", "MANIFEST.yaml")
    if not os.path.isfile(manifest_path):
        die(f"manifest not found: {manifest_path}")

    with open(manifest_path, "r", encoding="utf-8") as f:
        manifest = yaml.safe_load(f) or {}

    resources = manifest.get("resources", [])
    wrote = 0
    for r in resources:
        if r.get("status") not in ("current", "draft"):
            continue
        fmt = r.get("format")
        path = r.get("path")
        if not path:
            continue

        pdf_paths = []
        if fmt == "pdf" and path.endswith(".pdf"):
            pdf_paths = [path]
        elif fmt == "mixed" and path.endswith("/"):
            abs_dir = os.path.join(repo_root, path)
            if os.path.isdir(abs_dir):
                pdf_paths = [
                    os.path.join(path, name)
                    for name in sorted(os.listdir(abs_dir))
                    if name.lower().endswith(".pdf")
                ]

        for pdf_path in pdf_paths:
            if extract_one(repo_root, pdf_path, r["id"], r.get("license", "UNKNOWN")):
                wrote += 1

    print(f"[extract_pdf_text] done: {wrote} file(s) extracted")


if __name__ == "__main__":
    main()
